#ifndef WEB_H
#define WEB_H

/* Style */
#include "Arduino.h"
#include <WiFiClient.h>
#include <WebServer.h>
#include <ESPmDNS.h>
#include <esp-fs-webserver.h> // https://github.com/cotestatnt/esp-fs-webserver

namespace fs
{

    FSWebServer &GetmyWebServer();
    bool fs_server_setup();

    static const String page_style =
        "<style>"
        "body{background:#3498db;font-family:sans-serif;font-size:14px;color:#777;text-align:center;margin-top:50px;}"
        "form{background:#fff;max-width:350px;margin:75px auto;padding:30px;border-radius:5px;text-align:center;}"
        "h1,h3{color:#333;}"
        "input,select{width:100%;height:44px;border-radius:4px;margin:10px auto;font-size:15px;background:#f1f1f1;border:0;padding:0 15px;box-sizing:border-box;}"
        "input[type=range]{padding:0;}"
        "input[type=checkbox]{width:auto;height:auto;margin-right:5px;}"
        "input[type=button], .btn{background:#3498db;color:#fff;cursor:pointer;width:100%;height:44px;border-radius:4px;margin:10px auto;font-size:15px;border:0;}"
        ".slider-container, .input-container, .checkbox-container, .select-container{margin-bottom:15px;text-align:center;}"
        "label{font-weight:bold;display:block;margin-bottom:5px;}"
        "#bar,#prgbar{background-color:#f1f1f1;border-radius:10px}#bar{background-color:#3498db;width:0%;height:10px}"
        ".nav-btn{margin-bottom:10px !important;}"
        "</style>";

    /* Change Username and Password Page */
    static const String changeCredentialsPage =
        "<!DOCTYPE html><html><head><meta name='viewport' content='width=device-width, initial-scale=1'>" + page_style + "</head><body>"
        "<form name=changeForm>"
        "<h1>Change Credentials</h1>"
        "<div class='input-container'><label for='oldUser'>Old User ID</label><input id='oldUser' name=oldUser placeholder='Old User ID'></div>"
        "<div class='input-container'><label for='oldPwd'>Old Password</label><input id='oldPwd' name=oldPwd placeholder='Old Password' type=Password></div>"
        "<div class='input-container'><label for='newUser'>New User ID</label><input id='newUser' name=newUser placeholder='New User ID'></div>"
        "<div class='input-container'><label for='newPwd'>New Password</label><input id='newPwd' name=newPwd placeholder='New Password' type=Password></div>"
        "<input type=button class=btn value='Save' onclick='saveCredentials()'>"
        "</form>"
        "<script>"
        "function saveCredentials() {"
        "  const oldUser = document.changeForm.oldUser.value;"
        "  const oldPwd = document.changeForm.oldPwd.value;"
        "  const newUser = document.changeForm.newUser.value;"
        "  const newPwd = document.changeForm.newPwd.value;"
        "  if (oldUser && oldPwd && newUser && newPwd) {"
        "    fetch('/setCredentials', {"
        "      method: 'POST',"
        "      headers: { 'Content-Type': 'application/json' },"
        "      body: JSON.stringify({ oldUser, oldPwd, newUser, newPwd })"
        "    }).then(response => {"
        "      if (response.ok) alert('Credentials updated successfully!');"
        "      else alert('Failed to update credentials.');"
        "    });"
        "  } else {"
        "    alert('Please fill in all fields.');"
        "  }"
        "}"
        "</script></body></html>";

        /* WiFi and MQTT Settings Page */
        static const String wifiSettingsPage =
            "<!DOCTYPE html><html><head><meta name='viewport' content='width=device-width, initial-scale=1'>" + page_style + "</head><body>"
            "<form name=wifiForm>"
            "<h1>WiFi & MQTT Settings</h1>"
            "<h3>STA (Client) WiFi</h3>"
            "<div class='input-container'><label for='ssid'>WiFi SSID</label><input id=ssid name=ssid placeholder='WiFi SSID' /></div>"
            "<div class='input-container'><label for='pass'>WiFi Password</label><input id=pass name=pass placeholder='WiFi Password' type=password /></div>"
            "<h3>Access Point (AP)</h3>"
            "<div class='input-container'><label for='ap_ssid'>AP SSID</label><input id=ap_ssid name=ap_ssid placeholder='AP SSID' /></div>"
            "<div class='input-container'><label for='ap_pass'>AP Password</label><input id=ap_pass name=ap_pass placeholder='AP Password' type=password /></div>"
            "<h3>MQTT</h3>"
            "<div class='input-container'><label for='mqtt_server'>MQTT Server</label><input id=mqtt_server name=mqtt_server placeholder='MQTT Server' /></div>"
            "<div class='input-container'><label for='mqtt_port'>MQTT Port</label><input id=mqtt_port name=mqtt_port placeholder='MQTT Port' type=number /></div>"
            "<div class='input-container'><label for='mqtt_user'>MQTT User</label><input id=mqtt_user name=mqtt_user placeholder='MQTT User' /></div>"
            "<div class='input-container'><label for='mqtt_pass'>MQTT Password</label><input id=mqtt_pass name=mqtt_pass placeholder='MQTT Password' type=password /></div>"
            "<div class='input-container'><label for='mqtt_topic'>MQTT Topic</label><input id=mqtt_topic name=mqtt_topic placeholder='MQTT Topic' /></div>"
            "<div class='input-container'><label for='mqtt_cmd_topic'>MQTT Cmd Topic</label><input id=mqtt_cmd_topic name=mqtt_cmd_topic placeholder='MQTT Cmd Topic' /></div>"
            "<input type=button class=btn value='Save WiFi Settings' onclick='saveWifi()'>"
            "</form>"
            "<script>"
            "function saveWifi(){"
            "  const pass = document.getElementById('pass').value;"
            "  const ap_pass = document.getElementById('ap_pass').value;"
            "  const mqtt_pass = document.getElementById('mqtt_pass').value;"
            "  const payload = {"
            "    ssid: document.getElementById('ssid').value || '',"
            "    pass: (pass === '********') ? '' : pass,"
            "    ap_ssid: document.getElementById('ap_ssid').value || '',"
            "    ap_pass: (ap_pass === '********') ? '' : ap_pass,"
            "    mqtt_server: document.getElementById('mqtt_server').value || '',"
            "    mqtt_port: parseInt(document.getElementById('mqtt_port').value) || 0,"
            "    mqtt_user: document.getElementById('mqtt_user').value || '',"
            "    mqtt_pass: (mqtt_pass === '********') ? '' : mqtt_pass,"
            "    mqtt_topic: document.getElementById('mqtt_topic').value || '',"
            "    mqtt_cmd_topic: document.getElementById('mqtt_cmd_topic').value || ''"
            "  };"
            "  fetch('/setWifiSettings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)})"
            "    .then(r=>{ if (r.ok) alert('WiFi settings saved!'); else alert('Failed to save WiFi settings.'); });"
            "}"
            "function loadWifi(){"
            "  fetch('/getWifiSettings').then(r=>r.json()).then(d=>{"
            "    document.getElementById('ssid').value = d.ssid || '';"
            "    document.getElementById('pass').value = d.pass || '';"
            "    document.getElementById('ap_ssid').value = d.ap_ssid || '';"
            "    document.getElementById('ap_pass').value = d.ap_pass || '';"
            "    document.getElementById('mqtt_server').value = d.mqtt_server || '';"
            "    document.getElementById('mqtt_port').value = d.mqtt_port || 0;"
            "    document.getElementById('mqtt_user').value = d.mqtt_user || '';"
            "    document.getElementById('mqtt_pass').value = d.mqtt_pass || '';"
            "    document.getElementById('mqtt_topic').value = d.mqtt_topic || '';"
            "    document.getElementById('mqtt_cmd_topic').value = d.mqtt_cmd_topic || '';"
            "  }).catch(()=>{});"
            "}"
            "document.addEventListener('DOMContentLoaded', loadWifi);"
            "</script></body></html>";
    /* Server Index Page */
    static const String CarserverIndex =
        "<!DOCTYPE html>"
        "<html>"
        "<head>"
        "<meta name='viewport' content='width=device-width, initial-scale=1'>"
        "<title>ESP32 Control Panel</title>"
        "<style>"
        "body { background-color: #f0f2f5; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif; color: #333; margin: 0; padding: 20px; display: flex; justify-content: center; align-items: center; min-height: 100vh; box-sizing: border-box; }"
        ".container { background: #fff; max-width: 400px; width: 100%; margin: 20px auto; padding: 30px; border-radius: 8px; box-shadow: 0 4px 12px rgba(0,0,0,0.1); text-align: center; }"
        "h1 { color: #1a202c; font-size: 24px; margin-bottom: 20px; }"
        ".progress-container { margin-bottom: 20px; }"
        "#prg { font-size: 14px; color: #718096; margin-bottom: 5px; }"
        "#prgbar { background-color: #e2e8f0; border-radius: 10px; height: 12px; overflow: hidden; }"
        "#bar { background-color: #4299e1; width: 0%; height: 100%; border-radius: 10px; transition: width 0.3s ease-in-out; }"
        ".nav-grid { display: grid; grid-template-columns: 1fr; gap: 10px; }"
        ".btn { background-color: #4299e1; color: #fff; cursor: pointer; width: 100%; height: 48px; border-radius: 6px; font-size: 16px; font-weight: 500; border: 0; transition: background-color 0.2s; display: flex; justify-content: center; align-items: center; text-decoration: none; }"
        ".btn:hover { background-color: #3182ce; }"
        "</style>"
        "</head>"
        "<body>"
        "<div class='container'>"
        "<h1>ESP32 Control Panel</h1>"
        "<div class='progress-container'>"
        "<div id='prg'></div>"
        "<div id='prgbar'><div id='bar'></div></div>"
        "</div>"
        "<div class='nav-grid'>"
        "<a href='/timeDate' class='btn'>Set Time and Date</a>"
        "<a href='/bleUUID' class='btn'>Set BLE iBeacon UUID</a>"
        "<a href='/changeCredentials' class='btn'>Change Credentials</a>"
        "<a href='/imuThresholds' class='btn'>IMU Calibration</a>"
        "<a href='/womSettings' class='btn'>WOM Settings</a>"
        "<a href='/wifiSettings' class='btn'>WiFi / MQTT Settings</a>"
        "<a href='/timingSettings' class='btn'>Timing Settings</a>"
        "</div>"
        "</div>"
        "<script>"
        "document.addEventListener('DOMContentLoaded', function() {"
        "  const form = document.querySelector('form');"
        "  if (form) {"
        "    form.addEventListener('submit', function(e) {"
        "      e.preventDefault();"
        "      const data = new FormData(form);"
        "      const xhr = new XMLHttpRequest();"
        "      xhr.open('POST', '/update', true);"
        "      xhr.upload.addEventListener('progress', function(evt) {"
        "        if (evt.lengthComputable) {"
        "          const per = evt.loaded / evt.total;"
        "          const prg = document.getElementById('prg');"
        "          const bar = document.getElementById('bar');"
        "          if (prg) prg.innerHTML = 'Progress: ' + Math.round(per * 100) + '%';"
        "          if (bar) bar.style.width = Math.round(per * 100) + '%';"
        "        }"
        "      }, false);"
        "      xhr.onload = function() {"
        "        if (xhr.status >= 200 && xhr.status < 300) {"
        "          console.log('Success!');"
        "          alert('Update successful!');"
        "        } else {"
        "          console.log('Error: ' + xhr.status);"
        "          alert('Update failed.');"
        "        }"
        "      };"
        "      xhr.onerror = function() {"
        "        console.log('Error');"
        "        alert('Update failed.');"
        "      };"
        "      xhr.send(data);"
        "    });"
        "  }"
        "});"
        "function sub(obj){"
        "  var fileName = obj.value.split('\\\\');"
        "  var fileInput = document.getElementById('file-input');"
        "  if(fileInput) fileInput.innerHTML = '   '+ fileName[fileName.length-1];"
        "};"
        "</script>"
        "</body>"
        "</html>";

    /* Time and Date Page */
    static const String timeDatePage =
        "<!DOCTYPE html><html><head><meta name='viewport' content='width=device-width, initial-scale=1'>" + page_style + "</head><body>"
        "<form name=timeForm>"
        "<h1>Set Time and Date</h1>"
        "<div class='input-container' style='text-align:center;'><p>Current ESP32 Time: <span id='currentTime'>Loading...</span></p></div>"
        "<div class='input-container'><label for='datetime'>Select new Date and Time</label><input type='datetime-local' id='datetime' name='datetime'></div>"
        "<input type='button' class=btn value='Set Time' onclick='sendTime()'>"
        "</form>"
        "<script>"
        "function updateCurrentTime() {"
        "  fetch('/getCurrentTime')"
        "    .then(response => response.json())"
        "    .then(data => {"
        "      document.getElementById('currentTime').innerText = data.currentTime;"
        "    });"
        "}"
        "function sendTime() {"
        "  const datetime = document.getElementById('datetime').value;"
        "  if (datetime) {"
        "    fetch('/setTime', {"
        "      method: 'POST',"
        "      headers: { 'Content-Type': 'application/json' },"
        "      body: JSON.stringify({ datetime })"
        "    }).then(response => {"
        "      if (response.ok) alert('Time set successfully!');"
        "      else alert('Failed to set time.');"
        "    });"
        "  } else {"
        "    alert('Please select a valid date and time.');"
        "  }"
        "}"
        "document.addEventListener('DOMContentLoaded', () => {"
        "  updateCurrentTime();"
        "  const now = new Date();"
        "  const localDatetime = now.toISOString().slice(0, 16);"
        "  document.getElementById('datetime').value = localDatetime;"
        "});"
        "</script></body></html>";

    /* BLE iBeacon UUID Page */
    static const String bleUUIDPage =
        "<!DOCTYPE html><html><head><meta name='viewport' content='width=device-width, initial-scale=1'>" + page_style + "</head><body>"
        "<form name=uuidForm>"
        "<h1>Set BLE iBeacon UUID</h1>"
        "<div class='input-container' style='text-align:center;'><p>Current UUID: <br><span id='currentUUID'>Loading...</span></p></div>"
        "<div class='input-container'><label for='uuid'>New UUID</label><input id='uuid' name=uuid placeholder='Enter UUID'></div>"
        "<input type='button' class=btn value='Save UUID' onclick='saveUUID()'>"
        "</form>"
        "<script>"
        "function saveUUID() {"
        "  const uuid = document.uuidForm.uuid.value;"
        "  const uuidRegex = /^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/;"
        "  if (uuid && uuidRegex.test(uuid)) {"
        "    fetch('/setUUID', {"
        "      method: 'POST',"
        "      headers: { 'Content-Type': 'application/json' },"
        "      body: JSON.stringify({ uuid })"
        "    }).then(response => {"
        "      if (response.ok) alert('UUID saved successfully!');"
        "      else alert('Failed to save UUID.');"
        "    });"
        "  } else {"
        "    alert('Please enter a valid UUID in the format XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX.');"
        "  }"
        "}"
        "function updateCurrentUUID() {"
        "  fetch('/getCurrentUUID')"
        "    .then(response => response.json())"
        "    .then(data => {"
        "      document.getElementById('currentUUID').innerText = data.uuid;"
        "    });"
        "}"
        "document.addEventListener('DOMContentLoaded', () => {"
        "  updateCurrentUUID();"
        "});"
        "</script></body></html>";

    /* IMU Thresholds Page */
    static const String imuThresholdsPage =
        "<!DOCTYPE html><html><head><meta name='viewport' content='width=device-width, initial-scale=1'>" + page_style + "</head><body>"
        "<form name=imuForm>"
        "<h1>IMU Calibration - Motion Thresholds</h1>"
        "<h3>Linear Accel Thresholds (g)</h3>"
        "<div class='slider-container'><label>GX: <span id=val_gx></span></label>"
        "<input id=gx type=range min=0.003 max=0.01 step=0.0001 value=0.005 /></div>"
        "<div class='slider-container'><label>GY: <span id=val_gy></span></label>"
        "<input id=gy type=range min=0.003 max=0.01 step=0.0001 value=0.005 /></div>"
        "<div class='slider-container'><label>GZ: <span id=val_gz></span></label>"
        "<input id=gz type=range min=0.003 max=0.01 step=0.0001 value=0.005 /></div>"
        "<h3>Rotation Thresholds (deg)</h3>"
        "<div class='slider-container'><label>Roll: <span id=val_roll></span></label>"
        "<input id=roll type=range min=0.2 max=1.5 step=0.01 value=0.5 /></div>"
        "<div class='slider-container'><label>Yaw: <span id=val_yaw></span></label>"
        "<input id=yaw type=range min=0.2 max=1.5 step=0.01 value=0.5 /></div>"
        "<div class='slider-container'><label>Pitch: <span id=val_pitch></span></label>"
        "<input id=pitch type=range min=0.2 max=1.5 step=0.01 value=0.5 /></div>"
        "<input type=button class=btn value='Save IMU Thresholds' onclick='saveIMU()'>"
        "</form>"
        "<script>"
        "function updateValues() {"
        "  document.getElementById('val_gx').innerText = Number(document.getElementById('gx').value).toFixed(4);"
        "  document.getElementById('val_gy').innerText = Number(document.getElementById('gy').value).toFixed(4);"
        "  document.getElementById('val_gz').innerText = Number(document.getElementById('gz').value).toFixed(4);"
        "  document.getElementById('val_roll').innerText = Number(document.getElementById('roll').value).toFixed(2);"
        "  document.getElementById('val_yaw').innerText = Number(document.getElementById('yaw').value).toFixed(2);"
        "  document.getElementById('val_pitch').innerText = Number(document.getElementById('pitch').value).toFixed(2);"
        "}"
        "function saveIMU() {"
        "  const payload = {"
        "    M_TH_GX: parseFloat(document.getElementById('gx').value),"
        "    M_TH_GY: parseFloat(document.getElementById('gy').value),"
        "    M_TH_GZ: parseFloat(document.getElementById('gz').value),"
        "    M_TH_ROLL: parseFloat(document.getElementById('roll').value),"
        "    M_TH_YAW: parseFloat(document.getElementById('yaw').value),"
        "    M_TH_PITCH: parseFloat(document.getElementById('pitch').value)"
        "  };"
        "  fetch('/setImuThresholds',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)})"
        "    .then(r=>{ if (r.ok) alert('IMU thresholds saved!'); else alert('Failed to save IMU thresholds.'); });"
        "}"
        "document.addEventListener('DOMContentLoaded', () => {"
        "  fetch('/getImuThresholds').then(r=>r.json()).then(d=>{"
        "    document.getElementById('gx').value = d.M_TH_GX;"
        "    document.getElementById('gy').value = d.M_TH_GY;"
        "    document.getElementById('gz').value = d.M_TH_GZ;"
        "    document.getElementById('roll').value = d.M_TH_ROLL;"
        "    document.getElementById('yaw').value = d.M_TH_YAW;"
        "    document.getElementById('pitch').value = d.M_TH_PITCH;"
        "    updateValues();"
        "  }).catch(()=>updateValues());"
        "  ['gx','gy','gz','roll','yaw','pitch'].forEach(id=>document.getElementById(id).addEventListener('input',updateValues));"
       "});"
        "</script></body></html>";
    /* WOM Settings Page */
    static const String womSettingsPage =
        "<!DOCTYPE html><html><head><meta name='viewport' content='width=device-width, initial-scale=1'>" + page_style + "</head><body>"
        "<form name=womForm>"
        "<h1>WOM (Wake-on-Motion) Settings</h1>"
        "<div class='slider-container'><label>WOM Threshold (1-30): <span id=val_wom></span></label>"
        "<input id=wom_thr type=range min=1.0 max=30.0 step=0.1 value=15.0 /></div>"
        "<div class='select-container'><label for='wom_lpf'>Accelerometer LPF:</label>"
        "<select id=wom_lpf>"
        "<option value=0>ACCEL_LPF_0 (460Hz)</option>"
        "<option value=1>ACCEL_LPF_1 (184Hz)</option>"
        "<option value=2>ACCEL_LPF_2 (92Hz)</option>"
        "<option value=3>ACCEL_LPF_3 (41Hz)</option>"
        "<option value=4>ACCEL_LPF_4 (20Hz)</option>"
        "<option value=5>ACCEL_LPF_5 (10Hz)</option>"
        "<option value=6>ACCEL_LPF_6 (5Hz)</option>"
        "<option value=7>ACCEL_LPF_7 (460Hz alt)</option>"
        "</select></div>"
        "<div class='select-container'><label for='wom_rate'>Low-power Accel Output Rate:</label>"
        "<select id=wom_rate>"
        "<option value=0>0.24 Hz</option>"
        "<option value=1>0.49 Hz</option>"
        "<option value=2>0.98 Hz</option>"
        "<option value=3>1.95 Hz</option>"
        "<option value=4>3.91 Hz</option>"
        "<option value=5>7.81 Hz</option>"
        "<option value=6>15.63 Hz</option>"
        "<option value=7>31.25 Hz</option>"
        "<option value=8>62.50 Hz</option>"
        "<option value=9>125 Hz</option>"
        "<option value=10>250 Hz</option>"
        "<option value=11>500 Hz</option>"
        "</select></div>"
        "<div class='checkbox-container'><label for=acc_comr><input type=checkbox id=acc_comr />Enable Accelerometer Compare Mode</label></div>"
        "<input type=button class=btn value='Save WOM Settings' onclick='saveWOM()'>"
        "</form>"
        "<script>"
        "function updateWOMVal(){ document.getElementById('val_wom').innerText = Number(document.getElementById('wom_thr').value).toFixed(1); }"
        "function saveWOM(){"
        " const payload = {"
        "   WOM_THR: parseFloat(document.getElementById('wom_thr').value),"
        "   WOM_LPF: parseInt(document.getElementById('wom_lpf').value,10),"
        "   WOM_RATE: parseInt(document.getElementById('wom_rate').value,10),"
        "   ACC_COMR: document.getElementById('acc_comr').checked"
        " };"
        " fetch('/setWomSettings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)})"
        "  .then(r=>{ if (r.ok) alert('WOM settings saved!'); else alert('Failed to save WOM settings.'); });"
        "}"
        "document.addEventListener('DOMContentLoaded', ()=>{"
        " fetch('/getWomSettings').then(r=>r.json()).then(d=>{"
        "   document.getElementById('wom_thr').value = d.WOM_THR;"
        "   document.getElementById('wom_lpf').value = d.WOM_LPF;"
        "   document.getElementById('wom_rate').value = d.WOM_RATE;"
        "   document.getElementById('acc_comr').checked = d.ACC_COMR;"
        "   updateWOMVal();"
        " }).catch(()=>updateWOMVal());"
        " document.getElementById('wom_thr').addEventListener('input', updateWOMVal);"
        "});"
        "</script></body></html>";
        
    /* Timing Settings Page */
   static const String timingSettingsPage =
    "<!DOCTYPE html>"
    "<html><head>"
    "<meta name='viewport' content='width=device-width, initial-scale=1'>"
    + page_style + "</head><body>"
    "<form id='timingForm' onsubmit='return false;' style='background:#fff;max-width:350px;margin:75px auto;padding:30px;border-radius:5px;text-align:center;'>"
    "<h1>Timing Settings</h1>"
    "<div>"

    "<div class='slider-container'>"
    "<label>WiFi Timeout (seconds):</label><br>"
    "<input type='range' id='wifiTimeout' min='10' max='900' step='1'>"
    "<span id='wifiTimeoutValue' class='value-display'></span>"
    "</div>"

    "<div class='slider-container'>"
    "<label>No Motion Timeout (seconds):</label><br>"
    "<input type='range' id='noMotionTimeout' min='10' max='900' step='1'>"
    "<span id='noMotionTimeoutValue' class='value-display'></span>"
    "</div>"

    "<div class='slider-container'>"
    "<label>Secure Mode Timeout (seconds):</label><br>"
    "<input type='range' id='secureModeTimeout' min='10' max='900' step='1'>"
    "<span id='secureModeTimeoutValue' class='value-display'></span>"
    "</div>"

    "<div class='slider-container'>"
    "<label>Snapshot Timeout (seconds):</label><br>"
    "<input type='range' id='SnapShotTime' min='10' max='90000' step='1'>"
    "<span id='SnapShotTimeValue' class='value-display'></span>"
    "</div>"
    "</div>"

    "<input type='button' class='btn' value='Save Settings' onclick='saveSettings()'>"
    "<div id='message'></div>"
    "</form>"

    "<script>"
    "function updateValue(slider, display){"
    " display.textContent = formatTime(slider.value);"
    "}"
    
    "function formatTime(seconds) {"
    "  const numSeconds = Number(seconds);"
    "  if (numSeconds < 60) {"
    "    return numSeconds + ' seconds';"
    "  } else if (numSeconds < 3600) {"
    "    return (numSeconds / 60).toFixed(1).replace(/\\.0$/, '') + ' minutes';"
    "  } else {"
    "    return (numSeconds / 3600).toFixed(2).replace(/\\.00$/, '').replace(/(\\.\\d)0$/, '$1') + ' hours';"
    "  }"
    "}"

    "function initSliders(){"
    " const sliders=['wifiTimeout','noMotionTimeout','secureModeTimeout','SnapShotTime'];"
    " sliders.forEach(id=>{"
    "   const s=document.getElementById(id);"
    "   const d=document.getElementById(id+'Value');"
    "   if(s){ s.addEventListener('input',()=>updateValue(s,d)); }"
    " });"
    " fetchCurrentSettings();"
    "}"

    "async function fetchCurrentSettings(){"
    " try{"
    "   const r=await fetch('/getTimingSettings');"
    "   const data=await r.json();"
    "   if(data){"
    "     if(data.wifitm!==undefined) document.getElementById('wifiTimeout').value=Math.floor(data.wifitm/1000);"
    "     if(data.nomotiontm!==undefined) document.getElementById('noMotionTimeout').value=Math.floor(data.nomotiontm/1000);"
    "     if(data.securmodetm!==undefined) document.getElementById('secureModeTimeout').value=Math.floor(data.securmodetm/1000);"
    "     if(data.SnapShotTime!==undefined) document.getElementById('SnapShotTime').value=Math.floor(data.SnapShotTime/1000);"
    "   }"
    "   ['wifiTimeout','noMotionTimeout','secureModeTimeout','SnapShotTime'].forEach(id=>{"
    "     const el=document.getElementById(id);"
    "     const dv=document.getElementById(id+'Value');"
    "     if(el && dv) updateValue(el,dv);"
    "   });"
    " }catch(e){"
    "   showMessage('Error loading settings',true);"
    " }"
    "}"

    "async function saveSettings(){"
    " const settings={"
    "   wifitm:document.getElementById('wifiTimeout').value*1000,"
    "   nomotiontm:document.getElementById('noMotionTimeout').value*1000,"
    "   securmodetm:document.getElementById('secureModeTimeout').value*1000,"
    "   SnapShotTime:Number(document.getElementById('SnapShotTime').value)*1000"
    " };"

    " try{"
    "   const r=await fetch('/setTimingSettings',{"
    "     method:'POST',"
    "     headers:{'Content-Type':'application/json'},"
    "     body:JSON.stringify(settings)"
    "   });"
    "   if(r.ok)showMessage('Settings saved successfully!',false);"
    "   else showMessage('Error saving settings',true);"
    " }catch(e){"
    "   showMessage('Error saving settings',true);"
    " }"
    "}"

    "function showMessage(msg,err){"
    " const d=document.getElementById('message');"
    " d.textContent=msg;"
    " d.className=err?'error':'success';"
    "}"

    "document.addEventListener('DOMContentLoaded',initSliders);"
    "</script></body></html>";

}
#endif