#ifndef WEB_H
#define WEB_H

/* Style */
#include "Arduino.h"
#include <WiFiClient.h>
#include <WebServer.h>
#include <ESPmDNS.h>
#include <esp-fs-webserver.h> // https://github.com/cotestatnt/esp-fs-webserver

namespace fs
{

    FSWebServer &GetmyWebServer();
    bool fs_server_setup();

    static const String style =
        "<style>#file-input,input{width:100%;height:44px;border-radius:4px;margin:10px auto;font-size:15px}"
        "input{background:#f1f1f1;border:0;padding:0 15px}body{background:#3498db;font-family:sans-serif;font-size:14px;color:#777}"
        "#file-input{padding:0;border:1px solid #ddd;line-height:44px;text-align:left;display:block;cursor:pointer}"
        "#bar,#prgbar{background-color:#f1f1f1;border-radius:10px}#bar{background-color:#3498db;width:0%;height:10px}"
        "form{background:#fff;max-width:258px;margin:75px auto;padding:30px;border-radius:5px;text-align:center}"
        ".btn{background:#3498db;color:#fff;cursor:pointer}</style>";

    /* Change Username and Password Page */
    static const String changeCredentialsPage =
        "<form name=changeForm>"
        "<h1>Change Credentials</h1>"
        "<input name=oldUser placeholder='Old User ID'> "
        "<input name=oldPwd placeholder='Old Password' type=Password> "
        "<input name=newUser placeholder='New User ID'> "
        "<input name=newPwd placeholder='New Password' type=Password> "
        "<input type=button class=btn value='Save' onclick='saveCredentials()'>"
        "<script>"
        "function saveCredentials() {"
        "  const oldUser = document.changeForm.oldUser.value;"
        "  const oldPwd = document.changeForm.oldPwd.value;"
        "  const newUser = document.changeForm.newUser.value;"
        "  const newPwd = document.changeForm.newPwd.value;"
        "  if (oldUser && oldPwd && newUser && newPwd) {"
        "    fetch('/setCredentials', {"
        "      method: 'POST',"
        "      headers: { 'Content-Type': 'application/json' },"
        "      body: JSON.stringify({ oldUser, oldPwd, newUser, newPwd })"
        "    }).then(response => {"
        "      if (response.ok) alert('Credentials updated successfully!');"
        "      else alert('Failed to update credentials.');"
        "    });"
        "  } else {"
        "    alert('Please fill in all fields.');"
        "  }"
        "}"
        "</script>" +
        style;

        /* WiFi and MQTT Settings Page */
        static const String wifiSettingsPage =
            "<form name=wifiForm>"
            "<h1>WiFi & MQTT Settings</h1>"
            "<h3>STA (Client) WiFi</h3>"
            "<input id=ssid name=ssid placeholder='WiFi SSID' />"
            "<input id=pass name=pass placeholder='WiFi Password' type=password />"
            "<h3>Access Point (AP)</h3>"
            "<input id=ap_ssid name=ap_ssid placeholder='AP SSID' />"
            "<input id=ap_pass name=ap_pass placeholder='AP Password' type=password />"
            "<h3>MQTT</h3>"
            "<input id=mqtt_server name=mqtt_server placeholder='MQTT Server' />"
            "<input id=mqtt_port name=mqtt_port placeholder='MQTT Port' type=number />"
            "<input id=mqtt_user name=mqtt_user placeholder='MQTT User' />"
            "<input id=mqtt_pass name=mqtt_pass placeholder='MQTT Password' type=password />"
            "<input id=mqtt_topic name=mqtt_topic placeholder='MQTT Topic' />"
            "<input id=mqtt_cmd_topic name=mqtt_cmd_topic placeholder='MQTT Cmd Topic' />"
            "<br><br><input type=button class=btn value='Save WiFi Settings' onclick='saveWifi()'>"
            "<script>"
            "function saveWifi(){"
            "  const payload = {"
            "    ssid: document.getElementById('ssid').value || '',"
            "    pass: document.getElementById('pass').value || '',"
            "    ap_ssid: document.getElementById('ap_ssid').value || '',"
            "    ap_pass: document.getElementById('ap_pass').value || '',"
            "    mqtt_server: document.getElementById('mqtt_server').value || '',"
            "    mqtt_port: parseInt(document.getElementById('mqtt_port').value) || 0," 
            "    mqtt_user: document.getElementById('mqtt_user').value || '',"
            "    mqtt_pass: document.getElementById('mqtt_pass').value || '',"
            "    mqtt_topic: document.getElementById('mqtt_topic').value || '',"
            "    mqtt_cmd_topic: document.getElementById('mqtt_cmd_topic').value || ''"
            "  };"
            "  fetch('/setWifiSettings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)})"
            "    .then(r=>{ if (r.ok) alert('WiFi settings saved'); else alert('Failed to save WiFi settings'); });"
            "}"
            "function loadWifi(){"
            "  fetch('/getWifiSettings').then(r=>r.json()).then(d=>{"
            "    document.getElementById('ssid').value = d.ssid || '';"
            "    document.getElementById('pass').value = d.pass || '';"
            "    document.getElementById('ap_ssid').value = d.ap_ssid || '';"
            "    document.getElementById('ap_pass').value = d.ap_pass || '';"
            "    document.getElementById('mqtt_server').value = d.mqtt_server || '';"
            "    document.getElementById('mqtt_port').value = d.mqtt_port || '';"
            "    document.getElementById('mqtt_user').value = d.mqtt_user || '';"
            "    document.getElementById('mqtt_pass').value = d.mqtt_pass || '';"
            "    document.getElementById('mqtt_topic').value = d.mqtt_topic || '';"
            "    document.getElementById('mqtt_cmd_topic').value = d.mqtt_cmd_topic || '';"
            "  }).catch(()=>{});"
            "}"
            "document.addEventListener('DOMContentLoaded', loadWifi);"
            "</script>" +
            style;
    /* Server Index Page */
    static const String CarserverIndex =
        "<script src='https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>"
        "<br><br>"
        "<div id='prg'></div>"
        "<br><div id='prgbar'><div id='bar'></div></div><br></form>"
        "<button class=btn onclick=\"window.location.href='/timeDate'\">Set Time and Date</button>"
        "<br><br>"
        "<button class=btn onclick=\"window.location.href='/bleUUID'\">Set BLE iBeacon UUID</button>"
        "<br><br>"
        "<button class=btn onclick=\"window.location.href='/changeCredentials'\">Change Credentials</button>"
        "<br><br>"
        "<button class=btn onclick=\"window.location.href='/imuThresholds'\">IMU Calibration</button>"
        "<br><br>"
        "<button class=btn onclick=\"window.location.href='/womSettings'\">WOM Settings</button>"
        "<br><br>"
        "<button class=btn onclick=\"window.location.href='/wifiSettings'\">WiFi / MQTT Settings</button>"
        "<br><br>"
        "<button class=btn onclick=\"window.location.href='/timingSettings'\">Timing Settings</button>"
        "<script>"
        "function sub(obj){"
        "var fileName = obj.value.split('\\\\');"
        "document.getElementById('file-input').innerHTML = '   '+ fileName[fileName.length-1];"
        "};"
        "$('form').submit(function(e){"
        "e.preventDefault();"
        "var form = $('#upload_form')[0];"
        "var data = new FormData(form);"
        "$.ajax({"
        "url: '/update',"
        "type: 'POST',"
        "data: data,"
        "contentType: false,"
        "processData:false,"
        "xhr: function() {"
        "var xhr = new window.XMLHttpRequest();"
        "xhr.upload.addEventListener('progress', function(evt) {"
        "if (evt.lengthComputable) {"
        "var per = evt.loaded / evt.total;"
        "$('#prg').html('progress: ' + Math.round(per*100) + '%');"
        "$('#bar').css('width',Math.round(per*100) + '%');"
        "}"
        "}, false);"
        "return xhr;"
        "},"
        "success:function(d, s) {"
        "console.log('success!') "
        "},"
        "error: function (a, b, c) {"
        "}"
        "});"
        "});"
        "</script>" +
        style;

    /* Time and Date Page */
    static const String timeDatePage =
        "<form name=timeForm>"
        "<h1>Set Time and Date</h1>"
        "<p>Current ESP32 Time: <span id='currentTime'></span></p>"
        "<input type='datetime-local' id='datetime' name='datetime'>"
        "<input type='button' class=btn value='Set Time' onclick='sendTime()'>"
        "<script>"
        "function updateCurrentTime() {"
        "  fetch('/getCurrentTime')"
        "    .then(response => response.json())"
        "    .then(data => {"
        "      document.getElementById('currentTime').innerText = data.currentTime;"
        "    });"
        "}"
        "function sendTime() {"
        "  const datetime = document.getElementById('datetime').value;"
        "  if (datetime) {"
        "    fetch('/setTime', {"
        "      method: 'POST',"
        "      headers: { 'Content-Type': 'application/json' },"
        "      body: JSON.stringify({ datetime })"
        "    }).then(response => {"
        "      if (response.ok) alert('Time set successfully!');"
        "      else alert('Failed to set time.');"
        "    });"
        "  } else {"
        "    alert('Please select a valid date and time.');"
        "  }"
        "}"
        "document.addEventListener('DOMContentLoaded', () => {"
        "  updateCurrentTime();"
        "  const now = new Date();"
        "  const localDatetime = now.toISOString().slice(0, 16);"
        "  document.getElementById('datetime').value = localDatetime;"
        "});"
        "</script>" +
        style;

    /* BLE iBeacon UUID Page */
    static const String bleUUIDPage =
        "<form name=uuidForm>"
        "<h1>Set BLE iBeacon UUID</h1>"
        "<p>Current UUID: <span id='currentUUID'></span></p>"
        "<input name=uuid placeholder='Enter UUID'>"
        "<input type='button' class=btn value='Save UUID' onclick='saveUUID()'>"
        "<script>"
        "function saveUUID() {"
        "  const uuid = document.uuidForm.uuid.value;"
        "  if (uuid) {"
        "    fetch('/setUUID', {"
        "      method: 'POST',"
        "      headers: { 'Content-Type': 'application/json' },"
        "      body: JSON.stringify({ uuid })"
        "    }).then(response => {"
        "      if (response.ok) alert('UUID saved successfully!');"
        "      else alert('Failed to save UUID.');"
        "    });"
        "  } else {"
        "    alert('Please enter a valid UUID.');"
        "  }"
        "}"
        "function updateCurrentUUID() {"
        "  fetch('/getCurrentUUID')"
        "    .then(response => response.json())"
        "    .then(data => {"
        "      document.getElementById('currentUUID').innerText = data.uuid;"
        "    });"
        "}"
        "document.addEventListener('DOMContentLoaded', () => {"
        "  updateCurrentUUID();"
        "  const uuid = document.uuidForm.uuid.value;"
        "  if (uuid) {"
        "    document.getElementById('uuid').value = uuid;"
        "  }"
        "});"
        "</script>" +
        style;

    /* IMU Thresholds Page */
    static const String imuThresholdsPage =
        "<form name=imuForm>"
        "<h1>IMU Calibration - Motion Thresholds</h1>"
        "<p>Linear accel thresholds (g):</p>"
        "<label>GX <span id=val_gx></span></label>"
        "<input id=gx type=range min=0.003 max=0.01 step=0.0001 value=0.005 />"
        "<label>GY <span id=val_gy></span></label>"
        "<input id=gy type=range min=0.003 max=0.01 step=0.0001 value=0.005 />"
        "<label>GZ <span id=val_gz></span></label>"
        "<input id=gz type=range min=0.003 max=0.01 step=0.0001 value=0.005 />"
        "<p>Rotation thresholds (deg):</p>"
        "<label>ROLL <span id=val_roll></span></label>"
        "<input id=roll type=range min=0.2 max=1.5 step=0.01 value=0.5 />"
        "<label>YAW <span id=val_yaw></span></label>"
        "<input id=yaw type=range min=0.2 max=1.5 step=0.01 value=0.5 />"
        "<label>PITCH <span id=val_pitch></span></label>"
        "<input id=pitch type=range min=0.2 max=1.5 step=0.01 value=0.5 />"
        "<p>Wake-on-motion thresholds:</p>"
        ""
        "<br><br><input type=button class=btn value='Save IMU Thresholds' onclick='saveIMU()'>"
        "<script>"
        "function updateValues() {"
        "  document.getElementById('val_gx').innerText = Number(document.getElementById('gx').value).toFixed(4);"
        "  document.getElementById('val_gy').innerText = Number(document.getElementById('gy').value).toFixed(4);"
        "  document.getElementById('val_gz').innerText = Number(document.getElementById('gz').value).toFixed(4);"
        "  document.getElementById('val_roll').innerText = Number(document.getElementById('roll').value).toFixed(2);"
        "  document.getElementById('val_yaw').innerText = Number(document.getElementById('yaw').value).toFixed(2);"
        "  document.getElementById('val_pitch').innerText = Number(document.getElementById('pitch').value).toFixed(2);"
        "  document.getElementById('val_wom').innerText = Number(document.getElementById('wom').value).toFixed(1);"
        "}"
        "function saveIMU() {"
        "  const payload = {"
        "    M_TH_GX: parseFloat(document.getElementById('gx').value),"
        "    M_TH_GY: parseFloat(document.getElementById('gy').value),"
        "    M_TH_GZ: parseFloat(document.getElementById('gz').value),"
        "    M_TH_ROLL: parseFloat(document.getElementById('roll').value),"
        "    M_TH_YAW: parseFloat(document.getElementById('yaw').value),"
        "    M_TH_PITCH: parseFloat(document.getElementById('pitch').value)"
        "  };"
        "  fetch('/setImuThresholds',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)})"
        "    .then(r=>{ if (r.ok) alert('IMU thresholds saved'); else alert('Failed to save IMU thresholds'); });"
        "}"
        "document.addEventListener('DOMContentLoaded', () => {"
        "  fetch('/getImuThresholds').then(r=>r.json()).then(d=>{"
        "    document.getElementById('gx').value = d.M_TH_GX;"
        "    document.getElementById('gy').value = d.M_TH_GY;"
        "    document.getElementById('gz').value = d.M_TH_GZ;"
        "    document.getElementById('roll').value = d.M_TH_ROLL;"
        "    document.getElementById('yaw').value = d.M_TH_YAW;"
        "    document.getElementById('pitch').value = d.M_TH_PITCH;"
        "    updateValues();"
        "  }).catch(()=>updateValues());"
        "  ['gx','gy','gz','roll','yaw','pitch'].forEach(id=>document.getElementById(id).addEventListener('input',updateValues));"
       "});"
        "</script>" +
        style;
    /* WOM Settings Page */
    static const String womSettingsPage =
        "<form name=womForm>"
        "<h1>WOM (Wake-on-Motion) Settings</h1>"
        "<label>WOM Threshold (1 - 30): <span id=val_wom></span></label>"
        "<input id=wom_thr type=range min=1.0 max=30.0 step=0.1 value=15.0 />"
        "<p>Accelerometer LPF:</p>"
        "<select id=wom_lpf>"
        "<option value=0>ACCEL_LPF_0 (460Hz)</option>"
        "<option value=1>ACCEL_LPF_1 (184Hz)</option>"
        "<option value=2>ACCEL_LPF_2 (92Hz)</option>"
        "<option value=3>ACCEL_LPF_3 (41Hz)</option>"
        "<option value=4>ACCEL_LPF_4 (20Hz)</option>"
        "<option value=5>ACCEL_LPF_5 (10Hz)</option>"
        "<option value=6>ACCEL_LPF_6 (5Hz)</option>"
        "<option value=7>ACCEL_LPF_7 (460Hz alt)</option>"
        "</select>"
        "<p>Low-power accel output rate:</p>"
        "<select id=wom_rate>"
        "<option value=0>0.24 Hz</option>"
        "<option value=1>0.49 Hz</option>"
        "<option value=2>0.98 Hz</option>"
        "<option value=3>1.95 Hz</option>"
        "<option value=4>3.91 Hz</option>"
        "<option value=5>7.81 Hz</option>"
        "<option value=6>15.63 Hz</option>"
        "<option value=7>31.25 Hz</option>"
        "<option value=8>62.50 Hz</option>"
        "<option value=9>125 Hz</option>"
        "<option value=10>250 Hz</option>"
        "<option value=11>500 Hz</option>"
        "</select>"
        "<p>Compare Mode:</p>"
        "<input type=checkbox id=acc_comr /><label for=acc_comr>Enable Accelerometer Compare Mode</label>"
        "<br><br><input type=button class=btn value='Save WOM Settings' onclick='saveWOM()'>"
        "<script>"
        "function updateWOMVal(){ document.getElementById('val_wom').innerText = Number(document.getElementById('wom_thr').value).toFixed(1); }"
        "function saveWOM(){"
        " const payload = {"
        "   WOM_THR: parseFloat(document.getElementById('wom_thr').value),"
        "   WOM_LPF: parseInt(document.getElementById('wom_lpf').value,10),"
        "   WOM_RATE: parseInt(document.getElementById('wom_rate').value,10),"
        "   ACC_COMR: document.getElementById('acc_comr').checked"
        " };"
        " fetch('/setWomSettings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)})"
        "  .then(r=>{ if (r.ok) alert('WOM settings saved'); else alert('Failed to save WOM settings'); });"
        "}"
        "document.addEventListener('DOMContentLoaded', ()=>{"
        " fetch('/getWomSettings').then(r=>r.json()).then(d=>{"
        "   document.getElementById('wom_thr').value = d.WOM_THR;"
        "   document.getElementById('wom_lpf').value = d.WOM_LPF;"
        "   document.getElementById('wom_rate').value = d.WOM_RATE;"
        "   document.getElementById('acc_comr').checked = d.ACC_COMR;"
        "   updateWOMVal();"
        " }).catch(()=>updateWOMVal());"
        " document.getElementById('wom_thr').addEventListener('input', updateWOMVal);"
        "});"
        "</script>" +
        style ;
        
    /* Timing Settings Page */
    static const String timingSettingsPage =
        "<form name=timingForm>"
        "<h1>Timing Settings</h1>"
        "<div class=slider-container>"
        "<label>WiFi Timeout (seconds):</label><br>"
        "<input type=range id=wifiTimeout class=slider min=10 max=900 step=1>"
        "<span id=wifiTimeoutValue class=value-display></span>"
        "</div>"
        "<div class=slider-container>"
        "<label>No Motion Timeout (seconds):</label><br>"
        "<input type=range id=noMotionTimeout class=slider min=10 max=900 step=1>"
        "<span id=noMotionTimeoutValue class=value-display></span>"
        "</div>"
        "<div class=slider-container>"
        "<label>Secure Mode Timeout (seconds):</label><br>"
        "<input type=range id=secureModeTimeout class=slider min=10 max=900 step=1>"
        "<span id=secureModeTimeoutValue class=value-display></span>"
        "</div>"
        "<input type=button class=btn value='Save Settings' onclick='saveSettings()'>"
        "<div id=message></div>"
        "<script>"
        "function updateValue(slider, display) {"
        "  display.textContent = slider.value + ' seconds';"
        "}"
        "function initSliders() {"
        "  const sliders = ['wifiTimeout', 'noMotionTimeout', 'secureModeTimeout'];"
        "  sliders.forEach(id => {"
        "    const slider = document.getElementById(id);"
        "    const display = document.getElementById(id + 'Value');"
        "    slider.addEventListener('input', () => updateValue(slider, display));"
        "  });"
        "  fetchCurrentSettings();"
        "}"
        "async function fetchCurrentSettings() {"
        "  try {"
        "    const response = await fetch('/getTimingSettings');"
        "    const data = await response.json();"
        "    document.getElementById('wifiTimeout').value = Math.floor(data.wifitm / 1000);"
        "    document.getElementById('noMotionTimeout').value = Math.floor(data.nomotiontm / 1000);"
        "    document.getElementById('secureModeTimeout').value = Math.floor(data.securmodetm / 1000);"
        "    const sliders = ['wifiTimeout', 'noMotionTimeout', 'secureModeTimeout'];"
        "    sliders.forEach(id => {"
        "      const slider = document.getElementById(id);"
        "      const display = document.getElementById(id + 'Value');"
        "      updateValue(slider, display);"
        "    });"
        "  } catch (error) {"
        "    showMessage('Error loading settings', true);"
        "  }"
        "}"
        "async function saveSettings() {"
        "  const settings = {"
        "    wifitm: document.getElementById('wifiTimeout').value * 1000,"
        "    nomotiontm: document.getElementById('noMotionTimeout').value * 1000,"
        "    securmodetm: document.getElementById('secureModeTimeout').value * 1000"
        "  };"
        "  try {"
        "    const response = await fetch('/setTimingSettings', {"
        "      method: 'POST',"
        "      headers: { 'Content-Type': 'application/json' },"
        "      body: JSON.stringify(settings)"
        "    });"
        "    if (response.ok) {"
        "      showMessage('Settings saved successfully!', false);"
        "    } else {"
        "      showMessage('Error saving settings', true);"
        "    }"
        "  } catch (error) {"
        "    showMessage('Error saving settings', true);"
        "  }"
        "}"
        "function showMessage(message, isError) {"
        "  const messageDiv = document.getElementById('message');"
        "  messageDiv.textContent = message;"
        "  messageDiv.className = isError ? 'error' : 'success';"
        "}"
        "document.addEventListener('DOMContentLoaded', initSliders);"
        "</script>" +
        style;

}
#endif